sakuli:
    container_name: demo_sakuli
    image: consol/sakuli-ubuntu-xfce:dev
    volumes: 
    - ./example_xfce/:/root/my_test_suites/example_xfce
    environment:
    - TZ=Europe/Berlin
    - SAKULI_TEST_SUITE=/root/my_test_suites/example_xfce
    ports:
    - "5901:5901"
    - "6901:6901"
    command: "run /root/my_test_suites/example_xfce -loop 1" 
    #command: /bin/bash
    links: 
    - omd-labs:omd

omd-labs:
    container_name: demo_omd
    #image: consol/omd-labs-ubuntu-sakuli:dev
    image: local/sakuli-omd-labs-ubuntu:dev
    ports:
    - "8443:443"
